version: "3.8"

services:
  backend:
    build: .
    container_name: mpesa-backend
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mpesa-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: mpesa_db
      MYSQL_USER: mpesa_user
      MYSQL_PASSWORD: mpesa_pass123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
